trigger:
    - beta

pr: none

pool:
    vmImage: 'ubuntu-latest'

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
          npm install
      displayName: 'Install dependencies'
    - script:
        npm version minor 
        git status
      displayName: 'minor version'
    - script: |
          npm pack
      displayName: 'Package package'
    
    - task: CopyFiles@2
      inputs:
          contents: '*.tgz'
          targetFolder: $(Build.ArtifactStagingDirectory)
      displayName: 'Copy archives to artifacts staging directory'

    - task: PublishBuildArtifacts@1
      inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: package
      displayName: 'Publish artifacts'