# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: | 
    echo Hello, world!
    $releasesUrl = "https://api.github.com/repos/msgraph-typescript-typings/releases";

    Write-Host "Getting list of releases with '$($releasesUrl)'" -ForegroundColor Blue;
    $releasesJSON = Invoke-RestMethod -Uri $releasesUrl -Method Get;

    echo $releaseJSON
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
