# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  versionNum2: $(testVar)
  ${{ if ne(variables['versionNum2'], '') }}: 
    versionNum: $(testVar)
  ${{ if eq(variables['versionNum2'], '') }}: 
    versionNum: ''
steps:
- script: echo Hello, world! $(testVar)
  displayName: 'Run a one-line script'

- script: |
    echo read variables['testVar'].
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  displayName: 'Powershell task'
  #condition: eq(variables['testVar'], '')
  inputs:
    arguments: -testVar "${{ variables.versionNum }}"
    filePath: "$(System.DefaultWorkingDirectory)/scripts/src/CalculateNewProductionVersion.ps1"

- task: Npm@1
  displayName: 'Install packges in the scripts folder'
  inputs:
    workingDir: scripts
    verbose: false
    command: install

- task: Npm@1
  displayName: 'Update new production version in files $(testVar) $(env:NEW_VERSION_STRING)'
  inputs:
    workingDir: scripts
    verbose: false
    command: custom
    customCommand: 'run update:version -- --newVersion=$(NEW_VERSION_STRING)'
    



