# Validate the index.d.ts typings using dtslint

trigger:
- none

on:
  pr:
  branches: [dtslint]
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run dtslint
  displayName: 'npm install and build'

