# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# This action will automatically create a pull request against master if the pushed branch
# has a branch path spec like 1.0/pipelinebuild/*. Configure this action by updating the
# environment variable values[0]. 

name: "create pull request"

# Controls when the action will run. Triggers the workflow on push
# events but only for branches with the following branch spec: "v1.0/pipelinebuild/*"
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "create-pull-request"
  create-pull-request:
    # GitHub Actions don't support skip ci yet like Azure Pipelines so this check will do the same. 
    #if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu1804-README.md

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Create a pull request [1]
    - name: Create PR using the GitHub REST API via hub
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE_TITLE: Generated v1.0 typings using test
        MESSAGE_BODY: ""
        LABELS: generated
        BASE: master
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -l "$LABELS"
        echo "made"
# References
# [0] https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
# [1] https://hub.github.com/hub-pull-request.1.html
# https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
